name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install g++
        run: |
          sudo apt update
          sudo apt install g++-10

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run tests using make
        run: make test
